# Generated by Django 4.0.6 on 2022-07-26 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('support', models.BooleanField(default=False)),
                ('duration', models.PositiveIntegerField(default=30)),
                ('storage', models.IntegerField(default=10)),
                ('price', models.IntegerField(verbose_name=25)),
            ],
        ),
    ]
